### PR TITLE
fix(cli): angular cli fix #921

### LINKED ISSUE #921: cli: Add first primitives in an angular cli project
### Please provide the environment you discovered this bug in.

Angular CLI v20.3.4 and  @spartan-ng/cli@0.0.1-alpha.525 

### Which area/package is the issue in?

cli

### Description

I am using the command `ng g @spartan-ng/cli:ui` in an Angular CLI project. 
With the following option selection the primitives are not generated and errors are printed:

```bash
# buildable: true, generateAs: entrypoint
ng g @spartan-ng/cli:ui
Configuration file not found, creating a new one...
✔ Choose a directory to place your spartan libraries, e.g. libs/ui · libs/ui
✔ Should the libraries be buildable? (Y/n) · true
✔ How should we generate the components? · entrypoint
✔ What import alias should be used for the components? · @spartan-ng/helm
The specified library "ui-helm" couldn't be found in the workspace.

# buildable: false, generateAs: entrypoint
ng g @spartan-ng/cli:ui
Configuration file not found, creating a new one...
✔ Choose a directory to place your spartan libraries, e.g. libs/ui · libs/ui
✔ Should the libraries be buildable? (Y/n) · false
✔ How should we generate the components? · entrypoint
✔ What import alias should be used for the components? · @spartan-ng/helm
Cannot find tsconfig.base.json
```

I only selected button, but it errors also when all is selected.

---

The following options are working fine

```bash
# buildable: true, generateAs: library
ng g @spartan-ng/cli:ui
Configuration file not found, creating a new one...
✔ Choose a directory to place your spartan libraries, e.g. libs/ui · libs/ui
✔ Should the libraries be buildable? (Y/n) · true
✔ How should we generate the components? · library
✔ What import alias should be used for the components? · @spartan-ng/helm

# buildable: false, generateAs: library
ng g @spartan-ng/cli:ui
Configuration file not found, creating a new one...
✔ Choose a directory to place your spartan libraries, e.g. libs/ui · libs/ui
✔ Should the libraries be buildable? (Y/n) · false
✔ How should we generate the components? · library
✔ What import alias should be used for the components? · @spartan-ng/helm
``` 

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by MerlinMoos**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] autocomplete
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] button-group
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] empty
- [ ] dropdown-menu
- [ ] field
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-group
- [ ] input-otp
- [ ] item
- [ ] kbd
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] resizable
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] sidebar
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [x] cli

## What is the current behavior?

Closes #921 

## What is the new behavior?

spartan cli is not working for angular cli project

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/cli/src/utils/config.ts [hunk 1]
```diff
@@ -64,29 +79,43 @@ export async function getOrCreateConfig(tree: Tree, defaults?: Partial<Config>):
...
-		},
-		{
-			type: 'select',
-			choices: ['library', 'entrypoint'],
-			name: 'generateAs',
-			message: 'How should we generate the components?',
-			initial: 0,
-			skip: typeof defaults?.generateAs === 'string',
-		},
+		// Conditionally add Angular CLI–specific questions
```
Comment (goetzrobin) [inline libs/cli/src/utils/config.ts]:
```suggestion
		// Conditionally add Nx specific questions
```

File: libs/cli/src/generators/base/generator.ts [hunk 2]
```diff
@@ -27,8 +27,23 @@ function isAlreadyInstalled(tree: Tree, alias: string): boolean {
 	return alias in existingPaths;
 }
 
-function setupTsConfigAlias(tree: Tree, alias: string, targetLibDir: string) {
+function setupNGWorkspace(tree: Tree, alias: string, targetLibDir: string, { directory }: HlmBaseGeneratorSchema) {
```
Comment (goetzrobin) [inline libs/cli/src/generators/base/generator.ts]: Is there a better name.

NG Workspace and Nx Workspace sound too similar.

Maybe just setupPaathsForAngularCliProject ?

File: libs/cli/src/generators/base/lib/build-dependency-array.ts [hunk 3]
```diff
@@ -10,23 +11,28 @@ export function buildDependencyArray(
...
 
 export function buildDevDependencyArray(tree: Tree) {
 	const tailwindVersion = getTailwindVersion(tree);
 	return {
-		...(tailwindVersion === 4 && { 'tw-animate-css': TW_ANIMATE_CSS }),
+		...(tailwindVersion === 4 && { 'tw-animate-css': getLatestPkgVersion('tw-animate-css') }),
 	};
 }
+
+function getLatestPkgVersion(pkgName: string): string {
```
Comment (goetzrobin) [inline libs/cli/src/generators/base/lib/build-dependency-array.ts]: Can this throw an error?
Is there are more Nx way to get this?

File: apps/app/src/app/pages/(documentation)/documentation/components-json.page.ts [hunk 4]
```diff
@@ -57,35 +56,49 @@ export const routeMeta: RouteMeta = {
...
 	"componentsPath": "libs/ui",
+	"importAlias": "@spartan-ng/helm",
 	"buildable": true,
-	"generateAs": "library" | "entrypoint",
-	"importAlias": "@spartan-ng/helm"
+	"generateAs": "library" | "entrypoint"
 }'
 			/>
 
+			<spartan-section-sub-heading id="ng-configuration">NG Workspace Configuration</spartan-section-sub-heading>
```
Comment (goetzrobin) [inline apps/app/src/app/pages/(documentation)/documentation/components-json.page.ts]:
```suggestion
			<spartan-section-sub-heading id="ng-configuration">Angular CLI Project Configuration</spartan-section-sub-heading>
```

**Review by goetzrobin — CHANGES_REQUESTED** [review]
Couple minor comments. The one big thing is what is the right way to get the correct version for a package from the package.json. They might not have npm installed when they use yarn or bun.

Maybe we can use this instead: https://github.com/nrwl/nx/blob/a5d34fd9f9f2811945bbc653f91412a2be4ba7e1/packages/angular/src/generators/utils/version-utils.ts#L11

File: libs/cli/src/generators/base/lib/build-dependency-array.ts (hunk 3 above)
Comment (MerlinMoos) [reply libs/cli/src/generators/base/lib/build-dependency-array.ts]: sadly not, they kicked out the helper from nx...

Comment (MerlinMoos) [reply libs/cli/src/generators/base/lib/build-dependency-array.ts]: I found another way :)
