### PR TITLE
fix: select form control status dirtied on initial value and patchValue

### LINKED ISSUE #224: The select control become dirty on multiple mode with initlal value or patch value
If the select control is in multiple mode and I have an initial value or patch value (without interacting with the control), it incorrectly gets marked as dirty (`true`). This is incorrect because only when I interact with it should it become dirty, similar to `input` and other controls.

### Which area/package is the issue in?

select

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by thatsamsonkid**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

Currently just adds more test related to select's form control

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [x] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #224 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by thatsamsonkid** [comment]
Apart from the fix, keep me honest here i'm pretty sure this make sense. I've been spending some time in the material repo and playing around with mat-select component. I have below stackblitz for the material one if in case you guys find it helpful

https://stackblitz.com/edit/iwefen?file=src%2Fexample%2Fselect-error-state-matcher-example.ts

Apart from the fix also open to suggestions for how we can better organize the tests for select if anyone has any ideas especially since I added a bunch here for each scenario (single mode, multi-mode and required and initial value variants). But I also question if we need them all because we apply the statuses directly from ng control so its not really our logic per say. The root issue here was related more to when we triggered the form change. But yea let me know what you guys think 

@goetzrobin @elite-benni

**Comment by thatsamsonkid** [comment]
Need to rebase once #293 goes in

File: libs/ui/select/brain/src/lib/brn-select.component.ts [hunk 1]
```diff
@@ -155,6 +154,8 @@ export class BrnSelectComponent implements ControlValueAccessor, AfterContentIni
 	// eslint-disable-next-line @typescript-eslint/no-empty-function
 	private _onTouched = () => {};
 
+	private _shouldEmitValueChange = signal(false);
```
Comment (elite-benni) [inline libs/ui/select/brain/src/lib/brn-select.component.ts:157]: Is a signal really needed here?

**Review by elite-benni — APPROVED** [review]
looks good and well organized. ;) GJ

File: libs/ui/select/brain/src/lib/brn-select.component.ts (hunk 1 above)
Comment (thatsamsonkid) [reply libs/ui/select/brain/src/lib/brn-select.component.ts:157]: I guess technically it does not need to be a signal since this value only ever changes if writeValue is triggered or we change value internally. Does it matter you think or would you prefer to just have it has a regular variable?

Comment (elite-benni) [reply libs/ui/select/brain/src/lib/brn-select.component.ts:157]: I just stopped using signals everywhere. 
I think it is unnecessary overhead, even if the overhead of a signal is extremely small. 
If i is a signal, I will assume that there is something reacting on it.
These are just very small arguments and I am fine with keeping it a signal.
