### PR TITLE
fix: autocomplete and combobox popover content width in Safari

### LINKED ISSUE #1253: [BUG] Wrong autocomplete  popover content width
### Please provide the environment you discovered this bug in.

Spartan ng 643

MacOS 26.3
Safari

iOS 26.3
Safari / Brave

### Which area/package is the issue in?

autocomplete

### Description

The width of the content for the popover is wrong, leading to a very small content size for larger items.
The image below displays the issue on the SpartanNG page itself, but the same issue happens on iOS: Safari / Brave / Google browser (Google, not Google Chrome).

Image

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by sefatanam**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [x] autocomplete
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] button-group
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [x] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] empty
- [ ] dropdown-menu
- [ ] field
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-group
- [ ] input-otp
- [ ] item
- [ ] kbd
- [ ] label
- [ ] menubar
- [ ] native-select
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] resizable
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] sidebar
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?

Closes #1253 

## What is the new behavior?
The popover content of the Autocomplete and ComboBox components in Safari was not matching the width of their input fields. This issue has now been fixed so that the popover correctly inherits the width of the associated input.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/brain/autocomplete/src/lib/brn-autocomplete-search.ts [hunk 1]
```diff
@@ -78,7 +78,8 @@ export class BrnAutocompleteSearch<T> implements BrnAutocompleteBase<T>, Control
 	/** @internal The width of the search input wrapper */
 	public readonly searchInputWrapperWidth = computed<number | null>(() => {
 		const inputElement = this._searchInputWrapper()?.nativeElement;
-		return inputElement ? (inputElement.offsetWidth as number) : null;
+		if (!inputElement) return null;
+		return inputElement.getBoundingClientRect().width || inputElement.offsetWidth;
```
Comment (sefatanam) [inline libs/brain/autocomplete/src/lib/brn-autocomplete-search.ts:82]: Used `getBoundingClientRect`(Widely available across major browsers) for better Safari compatibility as it forces layout reflow. 
* https://caniuse.com/?search=getBoundingClientRect

**Comment by sefatanam** [comment]
You're welcome! Glad it worked 😊
