### PR TITLE
fix(dropdown-menu): remove button restriction from hlmDropdownMenuItem

### LINKED ISSUE #1125: AI assist dropdown invalid template
### Please provide the environment you discovered this bug in.

I noticed in the docs that the AI assist dropdown styling is messed up:

Image

### Which area/package is the issue in?

dropdown-menu

### Description

This is because the `hlmDropdownMenuItem` is used with an anchor element in [this template](https://github.com/spartan-ng/spartan/blob/main/apps/app/src/app/shared/page-options-dropdown/page-options-dropdown.ts) while the selector is only specified for `button`. This raises a question: should this template be updated or is `a` a valid element for `hlmDropdownMenuItem`? The selector for [CdkMenuItem](https://github.com/angular/components/blob/main/src/cdk/menu/menu-item.ts) doesn't have an element restriction at all so I think at least `a` should be allowed here? 

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by felhag**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] autocomplete
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] button-group
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] empty
- [x] dropdown-menu
- [ ] field
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-group
- [ ] input-otp
- [ ] item
- [ ] kbd
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] resizable
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] sidebar
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?
`hlmDropdownMenuItem` is restricted to `button`. This messes up the AI assist dropdown in the docs, but is also an unnecessary restriction imho. 

Closes #1125

## What is the new behavior?
`hlmDropdownMenuItem` matches on all elements

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ import { classes } from '@spartan-ng/helm/utils';
 	],
 	host: {
 		'data-slot': 'dropdown-menu-item',
-		'[disabled]': 'disabled() || null',
+		'[attr.disabled]': 'disabled() || null',
```
Comment (ashley-hunter) [inline libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts]: Following on from https://github.com/spartan-ng/spartan/issues/1125#issuecomment-3720977822

could we inject HOST_TAG_NAME here and use it to determine whether or not to add this attribute:

```suggestion
		'[attr.disabled]': '(tagName === "button" || tagName === "a") && disabled() ? "" : null',
```

Comment (felhag) [reply libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts]: Good suggestion, but should be add `[disabled]` for anchor elements too or just for buttons? It isn't officially supported although it does seem to work as expected.

Comment (ashley-hunter) [reply libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts]: Sorry - ignore the anchor part - I read your  comment mentioning buttons and a tags - and both were in my head when I was writing this 😂 but of course you're absolutely right. This should only be on a button.

Comment (marcjulian) [reply libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts]: Could we use `_disabled = computed(() => tagName === "button" && this.disabled() ? "" : null)` and use the value in host binding

Comment (ashley-hunter) [reply libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts]: Yes we could

Comment (felhag) [reply libs/helm/dropdown-menu/src/lib/hlm-dropdown-menu-item.ts]: Updated my pr. Choose a similar approach as in `brn-button`.
