### PR TITLE
fix: set shouldEmitValueChange to true on user change event for select

### LINKED ISSUE #303: bug: select doesn't recognize changes if the initial value and the first change is the same
### Please provide the environment you discovered this bug in.

```ts

@Component({
	selector: 'spartan-select-preview',
	standalone: true,
	imports: [BrnSelectImports, HlmSelectImports, ReactiveFormsModule],
	template: `
		<form [formGroup]="form">
		<brn-select class="inline-block" formControlName="value" placeholder="Select an option">
			<hlm-select-trigger class="w-56">
				<hlm-select-value />
			</hlm-select-trigger>
			<hlm-select-content>
				<hlm-option value="Refresh">Refresh</hlm-option>
				<hlm-option value="Settings">Settings</hlm-option>
				<hlm-option value="Help">Help</hlm-option>
				<hlm-option value="Signout">Sign out</hlm-option>
			</hlm-select-content>
		</brn-select>
</form>
	`,
})
export class SelectPreviewComponent {
	form = new FormGroup({
		value: new FormControl('Help'), // we have an initial value here
	});

	constructor() {
		this.form.valueChanges.subscribe((value) => {
			console.log(value); // the value you select will be skipped the first time
		});
	}

	ngOnInit() {
		setTimeout(() => {
			this.form.patchValue({ value: 'Help' }); // we set the same value again here asynchronously
		});
	}
}
```

### Which area/package is the issue in?

select

### Description

If we update the value asynchronously and set the same value as in the initial form value. The first selection will be skipped. 

### Please provide the exception or error you saw

_No response_

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by eneajaho**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix

## Which package are you modifying?

- [x] select

## What is the current behavior?

When we set the form value asynchronously the select won't respond to the first selection from the user (the form value won't be updated)

Closes #303 

## What is the new behavior?

Synchronously updating the form value doesn't break the initial selection from the user.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/ui/select/brain/src/lib/tests/select-reactive-form.ts [hunk 1]
```diff
@@ -96,6 +96,46 @@ export class SelectSingleValueWithInitialValueTestComponent {
...
+				<span class="text-destructive">Required</span>
+			}
+		</form>
+	`,
+})
+export class SelectSingleValueWithInitialValueWithAsyncUpdateTestComponent {
+	form = new FormGroup({ fruit: new FormControl('apple') });
+
+	constructor() {
+		// queueMicrotask(() => {
```
Comment (goetzrobin) [inline libs/ui/select/brain/src/lib/tests/select-reactive-form.ts:130]: Should this comment be removed?

Comment (eneajaho) [reply libs/ui/select/brain/src/lib/tests/select-reactive-form.ts:130]: I left it in case later a bug comes in and we can test it again based on different timing.

**Review by goetzrobin — APPROVED** [review]

**Review by thatsamsonkid — APPROVED** [review]
LGTM!
