### PR TITLE
feat(accordion): enhance accordion content and fix item change events

### LINKED ISSUE #927: accordion: accordion does not stay in sync when toggled programmatically and manually
### Please provide the environment you discovered this bug in.

https://spartan.ng/components/accordion

### Which area/package is the issue in?

accordion

### Description

**Steps to Reproduce:**

1. Open the “Multiple and Opened” accordion example in the docs.
2. Click “Toggle Third Item” — the third accordion item opens.
3. Manually toggle the same accordion item by clicking its header.
4. Click “Toggle Third Item” again.

https://github.com/user-attachments/assets/58165779-e38b-4f91-b560-dc55bd3aadae

**Observed Behavior:**
After manual interaction, the button no longer reflects the correct state. You must click it twice to update the third item again.

**Expected Behavior:**
The accordion should propagate internal state changes outward so external controls (like the example button) remain synchronized.

**Root Cause:**
The accordion updates its internal state but does not notify the parent signal (_thirdOpened) of the change.

**Proposed Solution:**
Expose either:

a model signal that binds to the opened state of each item, or

an openedChange output event to allow external state synchronization.

This will ensure consistent one-way and two-way interaction between programmatic and manual toggling.

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by goetzrobin**
move to width/height signals for dynamic content sizing instead of grid. move contents inert attribute to host element
move content style handlin to host element
add state-based outputs to item for better reactivity and synced docs

closes #927, #884

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [x] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] autocomplete
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] button-group
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-group
- [ ] input-otp
- [ ] kbd
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] sidebar
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?

Closes #927, #884

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

Adds stateChange and openedChange to API and removes an extra div from the hlm-accordion-content and brn-accordion-content components' template!

### CODE REVIEW

File: libs/brain/accordion/src/lib/brn-accordion-content.ts [hunk 1]
```diff
@@ -18,39 +23,65 @@ import { BrnAccordionItem } from './brn-accordion';
...
+		'[attr.inert]': '_addInert() ? true : undefined',
+		'[attr.style]': '_mutableContentStyle() ?? "opacity: 0;"',
 	},
 	template: `
-		<div [attr.inert]="_addInert()" style="overflow: hidden">
-			<p [class]="_contentClass()">
-				<ng-content />
-			</p>
-		</div>
+		<p [class]="_mutableContentClass()">
```
Comment (marcjulian) [inline libs/brain/accordion/src/lib/brn-accordion-content.ts]: Should we change this to a `div` like we have it in HlmAccordionContent? Because it's extended in HlmAccordionContent we have to write the template again anyways. 

Do you think we could turn it into a directive instead?

File: libs/brain/accordion/src/lib/brn-accordion-content.ts [hunk 2]
```diff
@@ -18,39 +23,65 @@ import { BrnAccordionItem } from './brn-accordion';
...
+	);
 
 	constructor() {
 		if (!this._item) {
 			throw Error('Accordion Content can only be used inside an AccordionItem. Add brnAccordionItem to parent.');
 		}
 	}
 
+	ngOnInit() {
+		if (isPlatformServer(this._platformId)) {
```
Comment (marcjulian) [inline libs/brain/accordion/src/lib/brn-accordion-content.ts]: You can use `afterNextRender` in the constructor and skip the check for the platform

File: libs/brain/accordion/src/lib/brn-accordion-content.ts (hunk 1 above)
Comment (goetzrobin) [reply libs/brain/accordion/src/lib/brn-accordion-content.ts]: Good point. let's make it a div. Turn: brn-accordion-content into a directive?

Comment (marcjulian) [reply libs/brain/accordion/src/lib/brn-accordion-content.ts]: Yes just thinking if we could turn brn-accordion-content into a directive. Because how hlm-accordion-content uses it is by extending the class which doesn't reuse the template of brn-accordion-content. Thats why we have in both components the template defined.

File: libs/brain/accordion/src/lib/brn-accordion-content.ts [hunk 3]
```diff
@@ -1,56 +1,62 @@
...
 	public readonly ariaLabeledBy = `brn-accordion-trigger-${this._item.id}`;
+	protected readonly _width = signal<number | null>(null);
+	protected readonly _height = signal<number | null>(null);
+	protected readonly _dimensionsInitiated = signal(false);
 
 	protected readonly _addInert = computed(() => (this.state() === 'closed' ? true : undefined));
 	/**
 	 * The class to be applied to the content element.
 	 */
 	public readonly contentClass = input<ClassValue>('');
```
Comment (marcjulian) [inline libs/brain/accordion/src/lib/brn-accordion-content.ts]: Probably not needed anymore in the directive

File: libs/helm/accordion/src/lib/hlm-accordion-content.ts [hunk 4]
```diff
@@ -5,25 +5,24 @@ import type { ClassValue } from 'clsx';
...
 	host: {
 		'[class]': '_computedClass()',
 	},
+	template: `
+		<div class="flex flex-col gap-4 text-balance pb-4 pt-0">
+			<ng-content />
+		</div>
+	`,
 })
 export class HlmAccordionContent extends BrnAccordionContent {
```
Comment (marcjulian) [inline libs/helm/accordion/src/lib/hlm-accordion-content.ts]: Could we use it as `hostDirectives: [BrnAccordionContent],`?
