### PR TITLE
fix(tabs): fix tab index when it's disabled #867

### LINKED ISSUE #867: Disabled tabs can be accessed using keys
### Please provide the environment you discovered this bug in.

"@angular/core": "19.2.14",
"@spartan-ng/brain": "0.0.1-alpha.484",

### Which area/package is the issue in?

tabs

### Description

# Spartan-ng Tabs Disabled Keyboard Navigation Issue

## Problem

Disabled tabs can be accessed using arrow keys in Spartan-ng Angular tabs, violating WAI-ARIA accessibility standards.

## Root Cause

**File**: `spartan-ng/brain/tabs/lib/brn-tabs-trigger.ts` - Line 21

```typescript
'[tabindex]': 'selected() ? "0": "-1"',
```

The tabindex logic only considers `selected()` state, ignoring `disabled()` state. When a disabled tab is selected, it has `tabindex="0"`, making it focusable by Angular CDK's `FocusKeyManager`.

## Solution

Update the tabindex host binding to consider disabled state:

```typescript
// Current (broken)
'[tabindex]': 'selected() ? "0": "-1"',

// Fixed
'[tabindex]': 'disabled() ? "-1" : (selected() ? "0" : "-1")',
```

## Logic

| Selected | Disabled | Current tabindex | Correct tabindex |
| -------- | -------- | ---------------- | ---------------- |
| ✓        | ✗        | "0"              | "0" ✓            |
| ✗        | ✗        | "-1"             | "-1" ✓           |
| ✓        | ✓        | "0" ❌           | "-1" ✓           |
| ✗        | ✓        | "-1"             | "-1" ✓           |

## References

- [Spartan-ng brn-tabs-trigger.ts](https://github.com/spartan-ng/spartan/blob/8c66d491e2196d44fe0ea0c92a0ea3b73cd8e51b/libs/brain/tabs/src/lib/brn-tabs-trigger.ts#L21)
- [WAI-ARIA Tabs Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by MerlinMoos**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-otp
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [x] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?

Closes #867 

## What is the new behavior?

tabindex is not -1 when it's disabled

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/brain/tabs/src/lib/brn-tabs-trigger.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ import { BrnTabs } from './brn-tabs';
 		'[id]': '_labelId()',
 		type: 'button',
 		role: 'tab',
-		'[tabindex]': 'selected() ? "0": "-1"',
+		'[tabindex]': '_disabled() ? "-1" : (selected() ? "0" : "-1")',
```
Comment (ashley-hunter) [inline libs/brain/tabs/src/lib/brn-tabs-trigger.ts]: I think technically this should be a number, as we are binding to the tabindex property, not the tabindex attribute.

```suggestion
		'[tabindex]': '_disabled() ? -1 : (selected() ? 0 : -1)',
```

**Review by ashley-hunter — APPROVED** [review]
All good! Thanks!
