### PR TITLE
fix(checkbox): Indeterminate state and Polish checkbox

### LINKED ISSUE #919: checkbox: Add export for CheckboxValue, if possible to keep checkbox value as boolean only
### Please provide the environment you discovered this bug in.

"@spartan-ng/brain": "^0.0.1-alpha.525",

### Which area/package is the issue in?

checkbox

### Description

I think it would be nice to export CheckboxValue.
If possible, it would also be good to keep the checkbox value as a boolean, and handle indeterminate as a separate input?

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by elite-benni**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] autocomplete
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] button-group
- [ ] calendar
- [ ] card
- [ ] carousel
- [x] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] empty
- [ ] dropdown-menu
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-group
- [ ] input-otp
- [ ] kbd
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] sidebar
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?

The Checkbox value is boolean | 'indeterminate', this should be split up into two inputs

Closes #919 

## What is the new behavior?

There are now two separate inputs for checked and indeterminate. 

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

if you passed indeterminate to the checkbox `checked` property. you now have to pass it it the new input property `indeterminate` instead of setting the `checked` property. 
The `checked` property now is a boolean.

### CODE REVIEW

File: libs/helm/checkbox/src/lib/hlm-checkbox.ts [hunk 1]
```diff
@@ -85,10 +85,13 @@ export class HlmCheckbox implements ControlValueAccessor {
 	public readonly ariaDescribedby = input<string | null>(null, { alias: 'aria-describedby' });
 
 	/** The checked state of the checkbox. */
-	public readonly checked = model<CheckboxValue>(false);
+	public readonly checked = model<boolean>(false);
 
-	/** Emits when checked state changes. */
-	public readonly checkedChange = output<CheckboxValue>();
```
Comment (MerlinMoos) [inline libs/helm/checkbox/src/lib/hlm-checkbox.ts:91]: Hey, can we please keep that. The write value is triggering a checkedChange event, which is sadly not correct when you patch a form via code and you have listeners on that field. the output is preventing that.

File: libs/brain/checkbox/src/lib/brn-checkbox.ts [hunk 2]
```diff
@@ -90,39 +90,39 @@ export class BrnCheckbox implements ControlValueAccessor, AfterContentInit, OnDe
...
 	/**
-	 * Current checked state of checkbox.
-	 * Can be boolean (true/false) or 'indeterminate'.
+	 * The checked state of the checkbox.
 	 * Can be bound with [(checked)] for two-way binding.
 	 */
-	public readonly checked = model<BrnCheckboxValue>(false);
-
-	/** Emits when checked state changes. */
-	public readonly checkedChange = output<BrnCheckboxValue>();
```
Comment (MerlinMoos) [inline libs/brain/checkbox/src/lib/brn-checkbox.ts:100]: same here (Hey, can we please keep that. The write value is triggering a checkedChange event, which is sadly not correct when you patch a form via code and you have listeners on that field. the output is preventing that.)

File: libs/helm/checkbox/src/lib/hlm-checkbox.ts (hunk 1 above)
Comment (elite-benni) [reply libs/helm/checkbox/src/lib/hlm-checkbox.ts:91]: Oh, thanks for the clarification why this was here in the first place, i will add a test for that.

File: libs/helm/checkbox/src/lib/hlm-checkbox.ts [hunk 3]
```diff
@@ -103,24 +106,21 @@ export class HlmCheckbox implements ControlValueAccessor {
 		disabled: signal(this.disabled()),
```
Comment (marcjulian) [inline libs/helm/checkbox/src/lib/hlm-checkbox.ts]: We could use a linkedSignal for `_disabled`

Comment (elite-benni) [reply libs/helm/checkbox/src/lib/hlm-checkbox.ts]: nice catch

File: libs/helm/checkbox/src/lib/hlm-checkbox.ts [hunk 4]
```diff
@@ -99,28 +106,24 @@ export class HlmCheckbox implements ControlValueAccessor {
 	/** Whether the checkbox is disabled. */
 	public readonly disabled = input<boolean, BooleanInput>(false, { transform: booleanAttribute });
 
-	protected readonly _state = computed(() => ({
-		disabled: signal(this.disabled()),
-	}));
+	protected readonly _disabled = linkedSignal(() => this.disabled());
```
Comment (MerlinMoos) [inline libs/helm/checkbox/src/lib/hlm-checkbox.ts]: we can keep it as it is but you can also do linkedSignal(this.disabled);

**Comment by MerlinMoos** [comment]
Look good to me thank you :) go ahead and merge it

File: apps/app/src/app/pages/(components)/components/(data-table)/selection-column.ts [hunk 5]
```diff
@@ -5,7 +5,11 @@ import { type CellContext, type HeaderContext, injectFlexRenderContext } from '@
 @Component({
 	imports: [HlmCheckboxImports],
 	template: `
-		<hlm-checkbox [checked]="_checkedState()" (checkedChange)="_context.table.toggleAllRowsSelected()" />
+		<hlm-checkbox
+			[checked]="_context.table.getIsAllRowsSelected()"
+			(checkedChange)="_context.table.toggleAllRowsSelected()"
```
Comment (marcjulian) [inline apps/app/src/app/pages/(components)/components/(data-table)/selection-column.ts]: Maybe move the output below the input.

File: libs/brain/checkbox/src/lib/brn-checkbox-form.spec.ts [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+	selector: 'brn-checkbox-form',
+	imports: [BrnCheckbox, FormsModule, CommonModule, ReactiveFormsModule],
+	template: `
+		<form [formGroup]="form">
+			<label>
+				Airplane mode is: {{ form.value.checkbox ? 'on' : 'off' }}
+				<brn-checkbox (checkedChange)="onCheckedChange($event)" formControlName="checkbox"></brn-checkbox>
+			</label>
+		</form>
+		{{ form.value | json }}
```
Comment (marcjulian) [inline libs/brain/checkbox/src/lib/brn-checkbox-form.spec.ts]: Remove json

File: libs/helm/checkbox/src/lib/hlm-checkbox-form.spec.ts [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+				Airplane mode is: {{ form.value.checkbox ? 'on' : 'off' }}
+				<hlm-checkbox
+					id="checkbox"
+					(checkedChange)="onCheckedChange($event)"
+					formControlName="checkbox"
+					aria-labelledby="testCheckbox"
+				></hlm-checkbox>
+			</label>
+		</form>
+		{{ form.value | json }}
```
Comment (marcjulian) [inline libs/helm/checkbox/src/lib/hlm-checkbox-form.spec.ts]: Remove json

**Comment by marcjulian** [comment]
I am also not sure if we should to it before v1, as we haven't documented it for other components either. I am fine with adding changes like that with v1 in the docs section.

**Comment by MerlinMoos** [comment]
hey @elite-benni can we merge it? Maybe you need to rebase main and update the snapshot
