### PR TITLE
fix(dialog): dynamic value disableClose #882

### LINKED ISSUE #882: dialog: disableClose doesn't work with dynamic value
### Please provide the environment you discovered this bug in.

"@spartan-ng/brain": "0.0.1-alpha.501",
"@spartan-ng/cli": "^0.0.1-alpha.494",
"@angular/animations": "20.1.2",
"@angular/cdk": "20.1.2",
"@angular/common": "20.1.2",
"@angular/compiler": "20.1.2",
"@angular/core": "20.1.2",

### Which area/package is the issue in?

dialog

### Description

`closeOnBackdropClick` or `disableClose` don’t work with dynamic values. If they are initially set to `true`, the dialog cannot be closed. But when I toggle canClose while the dialog is open, it still keeps the initial behavior.

```html
<hlm-dialog [closeOnBackdropClick]="canClose" [disableClose]="canClose"
```

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by MerlinMoos**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] autocomplete
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] button-group
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [x] dialog
- [ ] empty
- [ ] dropdown-menu
- [ ] field
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-group
- [ ] input-otp
- [ ] item
- [ ] kbd
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] resizable
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] sidebar
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?

Closes #882 #1187

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: libs/brain/dialog/src/lib/brn-dialog-ref.ts [hunk 1]
```diff
@@ -19,18 +20,28 @@ export class BrnDialogRef<DialogResult = any> {
 		return this.state() === 'open';
 	}
 
+	private readonly _options = signal<undefined | BrnDialogOptions>(undefined);
+	public readonly options = this._options.asReadonly();
+
+	public setOptions(options: Partial<BrnDialogOptions>) {
```
Comment (goetzrobin) [inline libs/brain/dialog/src/lib/brn-dialog-ref.ts]: setOptions might be confusing here because we use options.update

File: libs/brain/dialog/src/lib/brn-dialog-ref.ts [hunk 2]
```diff
@@ -19,18 +20,28 @@ export class BrnDialogRef<DialogResult = any> {
...
 	constructor(
 		private readonly _cdkDialogRef: DialogRef<DialogResult>,
 		private readonly _open: WritableSignal<boolean>,
 		public readonly state: Signal<BrnDialogState>,
 		public readonly dialogId: number,
-		private readonly _options?: BrnDialogOptions,
+		_options?: BrnDialogOptions,
 	) {
+		if (_options) {
+			this._options.set(_options);
```
Comment (goetzrobin) [inline libs/brain/dialog/src/lib/brn-dialog-ref.ts:34]: and then here we use set

File: libs/brain/dialog/src/lib/brn-dialog.service.ts [hunk 3]
```diff
@@ -79,7 +79,7 @@ export class BrnDialogService {
 				: this._positionBuilder.global().centerHorizontally().centerVertically());
 
 		let brnDialogRef!: BrnDialogRef;
-		let effectRef!: EffectRef;
+		const effectRef: EffectRef[] = [];
```
Comment (goetzrobin) [inline libs/brain/dialog/src/lib/brn-dialog.service.ts]: should this be effectRefs

File: libs/brain/dialog/src/lib/brn-dialog.service.ts [hunk 4]
```diff
@@ -153,44 +155,51 @@ export class BrnDialogService {
...
 
-		const closeOnBackdropClick = options?.closeOnBackdropClick ?? this._defaultOptions.closeOnBackdropClick;
-		if (closeOnBackdropClick) {
-			cdkDialogRef.backdropClick.pipe(takeUntil(destroyed$)).subscribe(() => {
-				brnDialogRef.close(undefined, options?.closeDelay);
-			});
-		}
+				const closeOnBackdropClick = options?.closeOnBackdropClick ?? this._defaultOptions.closeOnBackdropClick;
+				if (closeOnBackdropClick) {
+					cdkDialogRef.backdropClick.pipe(takeUntil(merge(destroyed$, optionsChanged$))).subscribe(() => {
```
Comment (goetzrobin) [inline libs/brain/dialog/src/lib/brn-dialog.service.ts:181]: what does the merge do here?

Comment (goetzrobin) [reply libs/brain/dialog/src/lib/brn-dialog.service.ts:181]: @greptileai can you explain that?

Comment (goetzrobin) [reply libs/brain/dialog/src/lib/brn-dialog.service.ts:181]: just testing the AI here lol

File: libs/brain/dialog/src/lib/brn-dialog.ts [hunk 5]
```diff
@@ -174,10 +174,22 @@ export class BrnDialog<TResult = unknown, TContext extends Record<string, unknow
...
+				}),
+			);
+		});
+
+		runInInjectionContext(this._injector, () => {
+			this._dialogStateEffectRefs.push(
+				effect(() => {
+					const ref = this._dialogRef();
+					if (!ref) return;
+					ref.setOptions(this._options());
```
Comment (goetzrobin) [inline libs/brain/dialog/src/lib/brn-dialog.ts]: should options move above the early return or is this by design?

File: libs/brain/dialog/src/lib/brn-dialog.ts [hunk 6]
```diff
@@ -186,44 +198,44 @@ export class BrnDialog<TResult = unknown, TContext extends Record<string, unknow
 		});
 	}
 
-	public close(result?: TResult, delay?: number) {
+	public close(result?: TResult, delay?: number): void {
```
Comment (goetzrobin) [inline libs/brain/dialog/src/lib/brn-dialog.ts:192]: we should probably add a lint rule if we want the explicit void or no

**Review by goetzrobin — COMMENTED** [review]
left some comments

File: libs/brain/dialog/src/lib/brn-dialog.ts (hunk 6 above)
Comment (MerlinMoos) [reply libs/brain/dialog/src/lib/brn-dialog.ts:192]: yes but not in this PR we are having round about 1k lint errors then

File: libs/brain/dialog/src/lib/brn-dialog-ref.ts [hunk 7]
```diff
@@ -19,18 +20,28 @@ export class BrnDialogRef<DialogResult = any> {
 		return this.state() === 'open';
 	}
 
+	private readonly _options = signal<undefined | BrnDialogOptions>(undefined);
+	public readonly options = this._options.asReadonly();
+
+	public updateOptions(options: Partial<BrnDialogOptions>) {
```
Comment (marcjulian) [inline libs/brain/dialog/src/lib/brn-dialog-ref.ts]: Should this function be below the constructor?
